apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd.yaml
  - rbac.yaml
  - gateway-class.yaml
  - deployment.yaml
images:
  - name: ghcr.io/zimme/bunny-hole-connector
    newTag: 0.1.0
